#!/usr/bin/env bash

# SCRIPT VERSION
GROUP_SETUP_VER=1
GROUP_SETUP_VER_FILE="/etc/ublue/dx-groups"

# make the directory if it doesn't exist
mkdir -p /etc/ublue

# Run script if updated
if [[ -f $GROUP_SETUP_VER_FILE ]]; then
  GROUP_SETUP_VER_RAN=$(cat "$GROUP_SETUP_VER_FILE")
  if [[ "$GROUP_SETUP_VER" = "$GROUP_SETUP_VER_RAN" ]]; then
    echo "Group setup has already run. Exiting..."
    exit 0
  fi
fi

# Function to append a group entry to /etc/group
append_group() {
  local group_name="$1"
  if ! grep -q "^$group_name:" /etc/group; then
    echo "Appending $group_name to /etc/group"
    grep "^$group_name:" /usr/lib/group | tee -a /etc/group >/dev/null
  fi
}

# Setup Groups
append_group docker
append_group incus-admin
append_group libvirt
append_group dialout

# Automatically assign users in the wheel group to DX groups
# This is the enterprise-grade approach found in Bluefin
wheelarray=($(getent group wheel | cut -d ":" -f 4 | tr ',' '\n'))
for user in "${wheelarray[@]}"; do
  if [[ -n "$user" ]]; then
    echo "Adding $user to DX groups..."
    usermod -aG docker "$user"
    usermod -aG incus-admin "$user"
    usermod -aG libvirt "$user"
    usermod -aG dialout "$user"
  fi
done

# Prevent future executions
echo "Writing state file"
echo "$GROUP_SETUP_VER" >"$GROUP_SETUP_VER_FILE"